var:
  url-repo: https://github.com/ludo2ne/ENSAI-2A-complements-info   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

website:
  title: "Compléments d'informatique"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Cours
        menu:
          - href: doc/cours/intro.qmd
            text: Introduction
          - href: doc/cours/tests-unitaires.qmd
            text: Tests unitaires
      - text: TP
        menu:
          - href: doc/tp/tp1.qmd
            text: TP 1
          - href: doc/tp/tp2.qmd
            text: TP 2
          - href: doc/tp/tp3.qmd
            text: TP 3
          - href: doc/tp/tp4.qmd
            text: TP 4
    right:
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Source code]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
